/**
 * Terminal replay frames for the Gemini Plan demo session.
 * Session ID: 99999999-9999-4999-a999-999999999999
 *
 * ~35 second arc, 25 frames.
 * Narrative: Gemini drafts a feature rollout plan; blocked awaiting user approval to write.
 */

import type { TerminalFrame } from '@/lib/demo/terminal-scheduler';

// ANSI helpers
const ESC = '\x1b';
const P = `${ESC}[36m$${ESC}[0m `;
const GREEN = (s: string): string => `${ESC}[32m${s}${ESC}[0m`;
const YELLOW = (s: string): string => `${ESC}[33m${s}${ESC}[0m`;
const CYAN = (s: string): string => `${ESC}[36m${s}${ESC}[0m`;
const BOLD = (s: string): string => `${ESC}[1m${s}${ESC}[0m`;
const DIM = (s: string): string => `${ESC}[2m${s}${ESC}[0m`;

export const geminiPlanFrames: TerminalFrame[] = [
  // 1. Resume command
  {
    atMs: 0,
    data: `${P}gemini chat --resume 99999999-9999-4999-a999-999999999999\r\n`,
  },

  // 2. Resume banner
  {
    atMs: 500,
    data: `${CYAN(BOLD('Gemini CLI v2.0.1'))} ${DIM('resumed session 99999999')}\r\n\r\n`,
  },

  // 3. read features file
  {
    atMs: 1200,
    data: `${P}cat ~/projects/my-other-app/src/features.md\r\n`,
  },

  // 4a. file contents chunk 1
  {
    atMs: 1500,
    data:
      `${DIM('# Feature Flags — my-other-app')}\r\n` +
      `\r\n` +
      `## Active\r\n` +
      `- \`dark-mode\` — enabled for 100% of users\r\n` +
      `- \`new-dashboard\` — enabled for beta group (15%)\r\n` +
      `- \`ai-suggestions\` — internal only\r\n`,
  },

  // 4b. file contents chunk 2
  {
    atMs: 1800,
    data:
      `\r\n` +
      `## Planned\r\n` +
      `- \`collaborative-editing\` — Q2 rollout\r\n` +
      `- \`advanced-search\` — needs design review\r\n` +
      `- \`webhook-integrations\` — pending security audit\r\n` +
      `\r\n` +
      `## Deprecated\r\n` +
      `- \`legacy-export\` — removed 2025-03-01\r\n`,
  },

  // 5. ls directory
  {
    atMs: 3500,
    data: `${P}ls ~/projects/my-other-app/src/\r\n`,
  },

  // 6. directory listing
  {
    atMs: 3800,
    data: `${CYAN('app/')}  ${CYAN('components/')}  ${CYAN('features.md')}  ${CYAN('hooks/')}  ${CYAN('lib/')}  ${CYAN('types/')}\r\n`,
  },

  // 6b. Also check lib
  {
    atMs: 4200,
    data: `${P}ls ~/projects/my-other-app/src/lib/\r\n`,
  },

  // 6c. lib contents
  {
    atMs: 4500,
    data: `${CYAN('api.ts')}  ${CYAN('auth.ts')}  ${CYAN('db.ts')}  ${CYAN('feature-flags.ts')}  ${CYAN('utils.ts')}\r\n`,
  },

  // 6d. cat feature-flags
  {
    atMs: 4800,
    data: `${P}cat ~/projects/my-other-app/src/lib/feature-flags.ts | head -15\r\n`,
  },

  // 6e. feature-flags contents
  {
    atMs: 5000,
    data:
      `${DIM('// src/lib/feature-flags.ts')}\r\n` +
      `${CYAN('export')} ${CYAN('const')} FLAGS = [\r\n` +
      `  { key: ${GREEN("'dark-mode'")}, enabled: ${CYAN('true')}, rollout: ${CYAN('100')} },\r\n` +
      `  { key: ${GREEN("'new-dashboard'")}, enabled: ${CYAN('true')}, rollout: ${CYAN('15')} },\r\n` +
      `  { key: ${GREEN("'ai-suggestions'")}, enabled: ${CYAN('true')}, rollout: ${CYAN('0')} },\r\n` +
      `  { key: ${GREEN("'collaborative-editing'")}, enabled: ${CYAN('false')}, rollout: ${CYAN('0')} },\r\n` +
      `] ${CYAN('as')} ${CYAN('const')}\r\n`,
  },

  // 7. Gemini thinking
  {
    atMs: 6200,
    data: `\r\n${YELLOW('Planning...')}\r\n\r\n`,
  },

  // 8a. Plan output chunk 1
  {
    atMs: 7000,
    data:
      `${BOLD('Feature Rollout Plan: collaborative-editing')}\r\n` +
      `${DIM('Generated by Gemini — awaiting your approval to write.')}\r\n\r\n`,
  },

  // 8b. Plan step 1
  {
    atMs: 9000,
    data:
      `${BOLD('Step 1:')} ${GREEN('Infrastructure')} — add operational transform (OT) service\r\n` +
      `  • Deploy ${CYAN('ot-server')} behind load balancer\r\n` +
      `  • Add Redis pub/sub channel per document\r\n` +
      `  • Smoke test: 10 concurrent writers, <50ms p95\r\n` +
      `\r\n`,
  },

  // 8c. Plan step 2
  {
    atMs: 11000,
    data:
      `${BOLD('Step 2:')} ${GREEN('Backend API')} — WebSocket upgrade path\r\n` +
      `  • Add ${CYAN('WS /api/documents/:id/collab')} endpoint\r\n` +
      `  • Session auth via JWT (same as REST)\r\n` +
      `  • Presence tracking: cursor positions + user colour\r\n` +
      `\r\n`,
  },

  // 8d. Plan step 3
  {
    atMs: 13000,
    data:
      `${BOLD('Step 3:')} ${GREEN('Frontend')} — collaborative cursor overlay\r\n` +
      `  • ${CYAN('<CollabCursors>')} component renders peer carets\r\n` +
      `  • Debounce local ops at 16ms (60fps)\r\n` +
      `  • Conflict resolution: last-write-wins with OT merge\r\n` +
      `\r\n`,
  },

  // 8e. Plan step 4
  {
    atMs: 15000,
    data:
      `${BOLD('Step 4:')} ${GREEN('Feature flag rollout')}\r\n` +
      `  • Week 1: internal only (0.1% traffic)\r\n` +
      `  • Week 2: beta group (15%)\r\n` +
      `  • Week 3: gradual ramp 15% → 50%\r\n` +
      `  • Week 4: GA if error rate <0.1%\r\n` +
      `\r\n`,
  },

  // 8f. Plan step 5
  {
    atMs: 17500,
    data:
      `${BOLD('Step 5:')} ${GREEN('Observability')}\r\n` +
      `  • Track: op latency, conflict rate, WS reconnects\r\n` +
      `  • Alert: conflict rate >5% sustained 5min\r\n` +
      `  • Dashboard: Grafana panel added to ${CYAN('ops-runbook')}\r\n` +
      `\r\n`,
  },

  // 8g. Plan step 6
  {
    atMs: 19500,
    data:
      `${BOLD('Step 6:')} ${GREEN('Rollback gate')}\r\n` +
      `  • Kill-switch: set ${CYAN('collaborative-editing=false')} in feature flags\r\n` +
      `  • Auto-rollback: if error rate spikes >2x baseline\r\n` +
      `  • PagerDuty alert on WS server restart loop\r\n` +
      `\r\n`,
  },

  // 8h. Plan step 7
  {
    atMs: 21500,
    data:
      `${BOLD('Step 7:')} ${GREEN('Docs + onboarding')}\r\n` +
      `  • Update README with collab architecture diagram\r\n` +
      `  • Record 2-min demo screencast\r\n` +
      `  • Add ${CYAN('CONTRIBUTING.md')} section on OT conventions\r\n` +
      `\r\n`,
  },

  // 8i. Plan step 8
  {
    atMs: 23500,
    data:
      `${BOLD('Step 8:')} ${GREEN('Post-launch review')}\r\n` +
      `  • 30-day retrospective with eng + product\r\n` +
      `  • Decide on persistence strategy for offline edits\r\n` +
      `  • Evaluate CRDT migration if OT conflict rate stays >2%\r\n` +
      `\r\n`,
  },

  // 8j. Plan summary line
  {
    atMs: 25500,
    data:
      `${DIM('─────────────────────────────────────────────────────')}\r\n` +
      `${BOLD('Estimated timeline:')} 4 weeks | ${BOLD('Risk level:')} ${YELLOW('medium')}\r\n` +
      `${DIM('─────────────────────────────────────────────────────')}\r\n\r\n`,
  },

  // 9. Awaiting approval message
  {
    atMs: 30000,
    data:
      `${YELLOW(BOLD('⚠ Awaiting approval'))} to write ${CYAN('~/projects/my-other-app/src/features.md')}\r\n` +
      `${DIM('Run: gemini approve — to confirm, or gemini reject — to cancel.')}\r\n\r\n`,
  },

  // 10. Session blocked indicator
  {
    atMs: 32000,
    data: `${DIM('(session paused — waiting for user input)')}\r\n`,
  },

  // 11. Final prompt (blocked)
  {
    atMs: 35000,
    data: `${YELLOW(P)}`,
  },
];
