import * as fs from 'node:fs';
import * as path from 'node:path';
import { NextRequest, NextResponse } from 'next/server';
import { withErrorBoundary } from '@/lib/api-handler';
import { BadRequestError } from '@/lib/errors';

// ─── Constants ────────────────────────────────────────────────────────────────

/** Hook entries from token-optimizer/examples/hooks-starter.json */
const PRECOMPACT_HOOK = {
  type: 'command',
  command:
    "echo 'COMPACTION GUIDANCE: Preserve code changes, key decisions, and file paths. Discard intermediate attempts, explanations, and verbose tool output.'",
};

const POSTTOOLUSE_HOOK = {
  matcher: 'Write|Edit',
  type: 'command',
  command: "echo 'File modified. Skip formatting explanations. The formatter handles it.'",
};

/** Embedded .claudeignore template from token-optimizer/examples/claudeignore-template */
const CLAUDEIGNORE_TEMPLATE = `# .claudeignore - Block unnecessary files from Claude Code context
#
# Generated by agendo token analyzer.
# Prevents system reminders from injecting modified files you don't need.

# Security (CRITICAL)
**/.env
**/.env.*
**/credentials.json
**/service-account*.json
**/*secret*
**/*password*
**/config/secrets/
.aws/
.ssh/

# Dependencies
**/node_modules/
**/venv/
**/__pycache__/
**/vendor/
**/.venv/
**/dist/
**/build/

# Databases
**/*.sqlite
**/*.db
**/migrations/

# Media (large, high-token)
**/*.jpg
**/*.jpeg
**/*.png
**/*.gif
**/*.mp4
**/*.mov
**/*.pdf
**/*.zip
**/*.tar.gz

# Build artifacts
**/*.log
**/*.cache
**/coverage/
**/.next/
**/.nuxt/

# OS files
**/.DS_Store
**/Thumbs.db

# Large data files
**/*.csv
`;

// ─── Helpers ──────────────────────────────────────────────────────────────────

function expandHome(p: string): string {
  const home = process.env.HOME ?? '/root';
  if (p === '~') return home;
  if (p.startsWith('~/')) return path.join(home, p.slice(2));
  return p;
}

/**
 * Atomically writes a file: writes to a temp path then renames.
 * Creates parent directories as needed.
 */
function atomicWrite(targetPath: string, content: string): void {
  const dir = path.dirname(targetPath);
  fs.mkdirSync(dir, { recursive: true });
  const tmp = `${targetPath}.agendo-tmp-${Date.now()}`;
  fs.writeFileSync(tmp, content, 'utf-8');
  fs.renameSync(tmp, targetPath);
}

/**
 * Backs up a file to ~/.claude/_backups/agendo-token-analyzer/{timestamp}/{basename}
 * before modifying it. No-op if the file doesn't exist.
 */
function backup(filePath: string): void {
  if (!fs.existsSync(filePath)) return;
  const ts = new Date().toISOString().replace(/[:.]/g, '-');
  const backupDir = expandHome(`~/.claude/_backups/agendo-token-analyzer/${ts}`);
  const basename = path.basename(filePath);
  fs.mkdirSync(backupDir, { recursive: true });
  fs.copyFileSync(filePath, path.join(backupDir, basename));
}

type ClaudeSettings = {
  hooks?: {
    PreCompact?: Array<{ type: string; command: string }>;
    PostToolUse?: Array<{ matcher?: string; type: string; command: string }>;
    [key: string]: unknown;
  };
  env?: Record<string, string>;
  [key: string]: unknown;
};

function readSettings(): { path: string; settings: ClaudeSettings } {
  const settingsPath = expandHome('~/.claude/settings.json');
  let settings: ClaudeSettings = {};
  if (fs.existsSync(settingsPath)) {
    try {
      settings = JSON.parse(fs.readFileSync(settingsPath, 'utf-8')) as ClaudeSettings;
    } catch {
      settings = {};
    }
  }
  return { path: settingsPath, settings };
}

// ─── Route handler ────────────────────────────────────────────────────────────

export const POST = withErrorBoundary(async (req: NextRequest) => {
  const body = (await req.json()) as { action?: string; value?: string };
  const { action, value } = body;

  if (!action) {
    throw new BadRequestError('action is required');
  }

  if (
    action !== 'add-precompact-hook' &&
    action !== 'add-posttooluse-hook' &&
    action !== 'set-autocompact' &&
    action !== 'create-claudeignore'
  ) {
    throw new BadRequestError(
      'action must be one of: add-precompact-hook, add-posttooluse-hook, set-autocompact, create-claudeignore',
    );
  }

  if (action === 'create-claudeignore') {
    const targetPath = expandHome('~/.claude/.claudeignore');
    backup(targetPath);
    atomicWrite(targetPath, CLAUDEIGNORE_TEMPLATE);
    return NextResponse.json({ ok: true });
  }

  // Both remaining actions modify settings.json
  const { path: settingsPath, settings } = readSettings();
  backup(settingsPath);

  if (action === 'add-precompact-hook') {
    if (!settings.hooks) settings.hooks = {};
    const existing = settings.hooks.PreCompact ?? [];
    const alreadyHas = existing.some((h) => h.command === PRECOMPACT_HOOK.command);
    if (!alreadyHas) {
      settings.hooks.PreCompact = [...existing, PRECOMPACT_HOOK];
    }
  } else if (action === 'add-posttooluse-hook') {
    if (!settings.hooks) settings.hooks = {};
    const existing = settings.hooks.PostToolUse ?? [];
    const alreadyHas = existing.some((h) => h.command === POSTTOOLUSE_HOOK.command);
    if (!alreadyHas) {
      settings.hooks.PostToolUse = [...existing, POSTTOOLUSE_HOOK];
    }
  } else if (action === 'set-autocompact') {
    if (!settings.env) settings.env = {};
    settings.env.CLAUDE_AUTOCOMPACT_PCT_OVERRIDE = value ?? '70';
  }

  atomicWrite(settingsPath, JSON.stringify(settings, null, 2) + '\n');
  return NextResponse.json({ ok: true });
});
